BEGIN;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-01-training-001', 'p1b-m1-01-training', 'physics-b-1', 'p1b-m1', 0, '第 1 题', '一运动质点在某瞬时位于矢径 $\\begin{array} { r l } { \\vec { r } } & { { } ( \\mathbf { x } , \\mathbf { y } ) } \\end{array}$ 的端点处,则其速度大小为', '["$\\\\frac { d r } { d t }$","$\\\\frac { d \\\\vec { r } } { d t }$","$\\\\frac { d \\\\vec { \\\\mathbf { \\\\nabla } } \\\\vec { r } \\\\| } { d t }$","$\\\\sqrt { \\\\left( \\\\frac { d x } { d t } \\\\right) ^ { 2 } + \\\\left( \\\\frac { d y } { d t } \\\\right) ^ { 2 } }$"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习一.pdf 第1题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-01-training-002', 'p1b-m1-01-training', 'physics-b-1', 'p1b-m1', 0, '第 2 题', '下述关于质点运动描述的表达式正确的是（    ）', '["$|\\\\Delta \\\\vec{r}| = \\\\Delta r$","$\\\\left| \\\\frac{d\\\\vec{r}}{dt} \\\\right| = \\\\frac{dr}{dt}$","$\\\\left| \\\\frac{d\\\\vec{r}}{dt} \\\\right| \\\\neq \\\\frac{dr}{dt}$","$|d\\\\vec{r}| \\\\neq ds$"]'::jsonb, '2', '[]'::jsonb, NULL, NULL, NULL, '**选项 (A)**：$|\\Delta \\vec{r}|$ 是位移的大小（直线距离），$\\Delta r = r_2 - r_1$ 是位矢模的增量。除非质点做通过原点的直线运动，否则二者不等。❌

**选项 (B)**：$\\left| \\frac{d\\vec{r}}{dt} \\right| = |\\vec{v}|$ 是速度大小；$\\frac{dr}{dt}$ 是位矢模的变化率（径向速率）。例如匀速圆周运动中 $\\frac{dr}{dt}=0$，但 $|\\vec{v}| \\neq 0$。❌

**选项 (C)**：速度大小通常不等于径向速率，符合一般曲线运动规律。✅

**选项 (D)**：在微积分极限意义下，$dt \\to 0$ 时弧长无限接近弦长，故 $|d\\vec{r}| = ds$。❌', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习一.pdf 第2题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-01-training-003', 'p1b-m1-01-training', 'physics-b-1', 'p1b-m1', 0, '第 3 题', '某质点作直线运动的运动学方程为 $x = 3 t - 5 t ^ { 3 } + 2$ ,则该质点作', '["匀加速直线运动,加速度沿x轴正方向","匀加速直线运动,加速度沿x轴负方向","变加速直线运动,加速度沿x轴正方向","变加速直线运动,加速度沿x轴负方向。"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习一.pdf 第3题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-01-training-004', 'p1b-m1-01-training', 'physics-b-1', 'p1b-m1', 0, '第 4 题', '一质点沿 $x$ 轴运动，其加速度 $a$ 与位置坐标 $x$ 的关系为 $a = 2 + 6x^2$（SI）。如果质点在原点处的速度为零，则质点在 $x=2\\text{m}$ 处的速度大小 $v$ 约为（    ）', '["$40\\\\text{m/s}$","$5\\\\text{m/s}$","$20\\\\text{m/s}$","$10\\\\text{m/s}$"]'::jsonb, '1', '[]'::jsonb, NULL, NULL, NULL, '本题属于质点运动学第二类问题，加速度是位置 $x$ 的函数。利用链式法则：

$$a = \\frac{dv}{dt} = \\frac{dv}{dx}\\frac{dx}{dt} = v\\frac{dv}{dx}$$

分离变量得 $v\\,dv = a\\,dx = (2+6x^2)\\,dx$。

代入初始条件 $x=0$ 时 $v=0$，$x=2$ 时速度为 $v$，两边积分：

$$\\int_0^v v\\,dv = \\int_0^2 (2+6x^2)\\,dx$$

$$\\frac{1}{2}v^2 = \\left[2x+2x^3\\right]_0^2 = 4+16 = 20$$

$$v = \\sqrt{40} \\approx 6.32\\text{m/s}$$

最接近 $5\\text{m/s}$，故选 **B**。', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习一.pdf 第4题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-01-training-005', 'p1b-m1-01-training', 'physics-b-1', 'p1b-m1', 2, '第 5 题', '一质点沿 x方向运动,其加速度随时间变化关系为 $a { = } 3 { + } 2 t$ 如果初始时质点的速度 $\\nu _ { 0 }$ 为 $5 \\mathrm { m / s }$ ,则当t为3s时,质点的速度v =', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["填空题"]'::jsonb, '力学练习一.pdf 第5题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-01-training-006', 'p1b-m1-01-training', 'physics-b-1', 'p1b-m1', 2, '第 6 题', '质点以加速度 $a { = } k t$ 作直线运动,式中 k为常数,设初速度为 $\\nu _ { 0 }$ ,求质点速度 v与时间t的函数关系', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["填空题"]'::jsonb, '力学练习一.pdf 第6题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-01-training-007', 'p1b-m1-01-training', 'physics-b-1', 'p1b-m1', 3, '第 7 题', '一质点在 xoy 平面上运动,运动方程为 $x { = } 3 t { + } 5$ $y = \\frac { 1 } { 2 } t ^ { 2 } + 3 t - 4$ 。求以下物理量并把它们表示成直角坐标系中的矢量形式。以时间t为变量,写出质点位置矢量的表示式;
(2)求出t=1s时刻和 $t { = } 2 \\mathbf { s }$ 时刻的位置矢量,计算这1秒内质点的位移;
(3)计算t=0s时刻到 $\\scriptstyle { t = 4 \\mathrm { s } }$ 时刻内的平均速度;
(4)求出质点速度矢量表示式,计算 $\\scriptstyle { t = 4 \\mathrm { s } }$ 时质点的速度;
(5)计算t=0s到t=4s内质点的平均加速度;
(6)求出质点加速度矢量的表示式,计算t=4s时质点的加速度。', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["计算题"]'::jsonb, '力学练习一.pdf 第7题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-01-training-008', 'p1b-m1-01-training', 'physics-b-1', 'p1b-m1', 3, '第 8 题', '一质点沿 x 轴运动,其加速度为 $a { = } 4 t$ ,已知 $\\scriptstyle { t = 0 }$ 时,质点位于 ${ x } _ { 0 } \\mathrm { { = } } 1 0 \\mathrm { { m } }$ 处,初速度 $\\scriptstyle \\nu _ { 0 } = 0$ 。试求其位置和时间的关系式。', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["计算题"]'::jsonb, '力学练习一.pdf 第8题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-01-training-009', 'p1b-m1-01-training', 'physics-b-1', 'p1b-m1', 3, '第 9 题', '一个质点沿 x 轴运动,其加速度和位置的关系为 $\\scriptstyle a = 2 + 6 x ^ { 2 }$ 。已知质点在 $x _ { 0 } { = } 0$ 处,速度为 $\\nu _ { 0 } { = } 1 0 m / s$ ,试求质点在任何坐标处的速度值。', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["计算题"]'::jsonb, '力学练习一.pdf 第9题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-02-training-001', 'p1b-m1-02-training', 'physics-b-1', 'p1b-m1', 0, '第 1 题', '下列说法中,哪一个是正确的？', '["一质点在某时刻的瞬时速度是2 m/s,说明它在此后1 s内一定要经过2 m的路程","斜向上抛的物体,在最高点处的速度最小,加速度最大","物体作曲线运动时,有可能在某时刻的法向加速度为零","物体加速度越大,则速度越大。"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习二.pdf 第1题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-02-training-002', 'p1b-m1-02-training', 'physics-b-1', 'p1b-m1', 0, '第 2 题', '质点作半径为 $R$ 的变速圆周运动时的加速度大小为（   ）（$v$ 表示任一时刻质点的速率）', '["$\\\\frac{dv}{dt}$","$\\\\frac{v^2}{R}$","$\\\\frac{v^2}{R} + \\\\frac{dv}{dt}$","$\\\\sqrt{\\\\left(\\\\frac{v^2}{R}\\\\right)^2 + \\\\left(\\\\frac{dv}{dt}\\\\right)^2}$"]'::jsonb, '3', '[]'::jsonb, NULL, NULL, NULL, '变速圆周运动的加速度由两个互相垂直的分量组成：

- **切向加速度**：$a_t = \\frac{dv}{dt}$，改变速度大小。
- **法向加速度**：$a_n = \\frac{v^2}{R}$，改变速度方向。

加速度是矢量，需用勾股定理合成：

$$a = \\sqrt{a_n^2 + a_t^2} = \\sqrt{\\left(\\frac{v^2}{R}\\right)^2 + \\left(\\frac{dv}{dt}\\right)^2}$$

故选 **D**。

注意：匀速圆周运动时 $\\frac{dv}{dt}=0$，则 $a=\\frac{v^2}{R}$（对应选项 B）。', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习二.pdf 第2题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-02-training-003', 'p1b-m1-02-training', 'physics-b-1', 'p1b-m1', 0, '第 3 题', '在一个转动的齿轮上,一个齿尖 P 沿半径为 R=0.2m 的圆周运动,其路程 S 随时间的变化规律为 $S = \\nu _ { 0 } t + { \\frac { 1 } { 2 } } b t ^ { 2 }$ ,其中 $\\nu _ { 0 } { = } 2 \\mathrm { m / s }$ 和 $b = 0 . 3 m / s ^ { 2 }$ 0则t=5s时齿尖P的总加速度大小a约等于', '["$3 4 \\\\mathrm { m } / \\\\mathrm { s } ^ { 2 }$","$4 2 \\\\mathrm { m } / \\\\mathrm { s } ^ { 2 }$","$5 1 \\\\mathrm { m } / \\\\mathrm { s } ^ { 2 }$","$6 1 \\\\mathrm { m } / \\\\mathrm { s } ^ { 2 }$"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习二.pdf 第3题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-02-training-004', 'p1b-m1-02-training', 'physics-b-1', 'p1b-m1', 0, '第 4 题', '质点的质量为 $m$，置于光滑球面的顶点 $A$ 处（球面固定不动），如图所示。当它由静止开始下滑到球面上 $B$ 点时（设 $OB$ 与竖直方向夹角为 $\\theta$），它的加速度的大小为（   ）', '["$a = g\\\\sqrt{1 - \\\\cos\\\\theta}$","$a = g\\\\sin\\\\theta$","$a = g$","$a = g\\\\sqrt{4\\\\sin^2\\\\theta + (1 - \\\\cos\\\\theta)^2}$"]'::jsonb, '3', '[]'::jsonb, NULL, NULL, NULL, '质点在光滑球面上运动，只有重力做功，机械能守恒。下降高度 $h = R(1-\\cos\\theta)$，故：

$$mgR(1-\\cos\\theta) = \\frac{1}{2}mv^2$$

$$v^2 = 2gR(1-\\cos\\theta)$$

在自然坐标系下：

- **法向加速度**：$a_n = \\frac{v^2}{R} = 2g(1-\\cos\\theta)$
- **切向加速度**：$a_t = g\\sin\\theta$

总加速度大小为：

$$a = \\sqrt{a_n^2 + a_t^2} = g\\sqrt{4(1-\\cos\\theta)^2 + \\sin^2\\theta}$$

故选 **D**。', NULL, NULL, '/physics/training/p1b-m1-02-training/d9ee40d816856f6b75588d5c5adde7fbe6076a36381795ded5d2220b3ba1b1f9.jpg', 1, '["选择题"]'::jsonb, '力学练习二.pdf 第4题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-02-training-005', 'p1b-m1-02-training', 'physics-b-1', 'p1b-m1', 0, '第 5 题', '一质点从静止出发沿半径为 R=3m 的圆周运动,切向加速度恒为 $a _ { \\tau } = 8 m / s ^ { 2 }$ ,经时间t总加速度恰好与半径成 π/4角,则t等于', '["$\\\\frac { \\\\sqrt { 6 } } { 4 }$","$\\\\frac { \\\\sqrt { 6 } } { 2 }$","$\\\\frac { \\\\sqrt { 3 } } { 2 }$","$\\\\frac { \\\\sqrt { 2 } } { 3 }$"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习二.pdf 第5题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-02-training-006', 'p1b-m1-02-training', 'physics-b-1', 'p1b-m1', 2, '第 6 题', '质点沿半径为 R 的圆周运动,运动学方程为 $\\theta = 3 + 2 t ^ { 2 }$ ,则时刻质点的法向加速度大小为 $a _ { n } \\mathrm { { : } }$ = \\_;角加速度 $\\beta =$', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["填空题"]'::jsonb, '力学练习二.pdf 第6题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-02-training-007', 'p1b-m1-02-training', 'physics-b-1', 'p1b-m1', 2, '第 7 题', '在半径为 R 的圆周上运动的质点,其速率与时间关系为$\\scriptstyle \\nu = c t ^ { 2 }$ (式中c为常量),则从t=0到t时刻质点走过的路程St时刻质点的切向加速度 $a _ { t } \\mathrm { = }$ \\_;t时刻质点的法向加速度 $a _ { n } \\overline { { \\mathbf { \\Omega } } }$', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["填空题"]'::jsonb, '力学练习二.pdf 第7题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-02-training-008', 'p1b-m1-02-training', 'physics-b-1', 'p1b-m1', 2, '第 8 题', '在水平飞行的飞机上向前发射一颗炮弹,发射后飞机的速度为 $\\nu _ { 0 }$ ,炮弹相对于飞机的速度为 v,略去空气阻力,则以地球为参考系,炮弹的轨迹方程为 ;(2)以飞机为参考系,炮弹的轨迹方程为(设两种参考系中坐标原点均在发射处,x轴沿速度方向向前,y轴竖直向下)', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["填空题"]'::jsonb, '力学练习二.pdf 第8题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-02-training-009', 'p1b-m1-02-training', 'physics-b-1', 'p1b-m1', 2, '第 9 题', '飞轮作加速转动时,轮边缘上一点的运动学方程为 $S { = } 0 . 1 t ^ { 3 }$ 飞轮半径为 2m。当此点的速率 v=30m/s 时,其切向加速度为 \\_,法向加速度为', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["填空题"]'::jsonb, '力学练习二.pdf 第9题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-02-training-010', 'p1b-m1-02-training', 'physics-b-1', 'p1b-m1', 3, '第 10 题', '由楼窗口以水平初速度 $\\overrightarrow { \\nu _ { 0 } }$ 射出一发子弹,射出时子弹离地面的高度为 h,取枪口为原点,沿 $\\overrightarrow { \\nu _ { 0 } }$ 方向为 x轴,竖直向下为 y轴,并取发射时刻t为0,试求：子弹在任一时刻 的位置坐标及轨迹方程;
(2)子弹在t时刻的速度,切向加速度和法向加速度;
(3)子弹轨道落地处的曲率半径。', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["计算题"]'::jsonb, '力学练习二.pdf 第10题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-03-training-001', 'p1b-m1-03-training', 'physics-b-1', 'p1b-m1', 0, '第 1 题', '在足够长的管中装有粘滞液体，放入钢球由静止开始向下运动，下列说法中正确的是：（    ）', '["钢球运动越来越慢，最后静止不动","钢球运动越来越慢，最后达到稳定的速度","钢球运动越来越快，一直无限制地增加","钢球运动越来越快，最后达到稳定的速度"]'::jsonb, '3', '[]'::jsonb, NULL, NULL, NULL, '钢球在粘滞液体中向下运动时，受三个力：竖直向下的重力 $G$、竖直向上的浮力 $F_{浮}$ 和竖直向上的粘滞阻力 $f$。粘滞阻力 $f$ 随速度增大而增大。

1. **初始状态**：$v=0$，$f=0$，因钢球密度大于液体，$G > F_{浮}$，合力向下，钢球开始向下加速。
2. **加速过程**：随着 $v$ 增大，$f$ 增大，向下的合力 $F_{合}=G-F_{浮}-f$ 逐渐减小，加速度 $a$ 逐渐减小。但只要 $F_{合}>0$，速度仍在增大。
3. **最终状态**：当 $G = F_{浮}+f$ 时，$F_{合}=0$，$a=0$，钢球以此时的速度向下做匀速直线运动，即达到**收尾速度（Terminal Velocity）**。

因此钢球运动越来越快，最后达到稳定的速度。故选 **D**。', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习三.pdf 第1题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-03-training-002', 'p1b-m1-03-training', 'physics-b-1', 'p1b-m1', 0, '第 2 题', '质量分别为 $m$ 和 $M$ 的滑块 $A$ 和 $B$，叠放在光滑水平桌面上，如图所示。$A$、$B$ 间静摩擦系数为 $\\mu_s$，滑动摩擦系数为 $\\mu_k$，系统原处于静止。今有一水平力作用于 $A$ 上，要使 $A$、$B$ 不发生相对滑动，则应有（    ）', '["$F \\\\leq \\\\mu_s mg$","$F \\\\leq \\\\mu_s (1 + m/M)mg$","$F \\\\leq \\\\mu_s (m+M)mg$","$F \\\\leq \\\\mu_s mg \\\\frac{m}{M}$"]'::jsonb, '1', '[]'::jsonb, NULL, NULL, NULL, '要使 $A$、$B$ 不发生相对滑动，两者必须保持相对静止，即具有相同加速度。此时 $A$、$B$ 之间的摩擦力为静摩擦力。

**整体法**：将 $A$、$B$ 看作整体，总质量为 $(M+m)$，只受水平拉力 $F$：

$$F = (M+m)a$$

**隔离法**：单独分析滑块 $B$，水平方向只受 $A$ 对 $B$ 的静摩擦力 $f$：

$$f = Ma$$

临界条件为静摩擦力达到最大静摩擦力：

$$f_{max} = \\mu_s N_A = \\mu_s mg$$

（$N_A$ 是 $A$ 对 $B$ 的压力，大小等于 $A$ 的重力 $mg$）

由隔离法得系统最大加速度：

$$Ma_{max} = \\mu_s mg \\Rightarrow a_{max} = \\frac{\\mu_s mg}{M}$$

代入整体法：

$$F_{max} = (M+m)a_{max} = (M+m)\\cdot\\frac{\\mu_s mg}{M} = \\mu_s mg\\left(1+\\frac{m}{M}\\right)$$

故选 **B**。', NULL, NULL, '/physics/training/p1b-m1-03-training/fa05c9f7443c261e509c0a00757428cdfaeed2a7f62dc8b730aba305f38e990b.jpg', 1, '["选择题"]'::jsonb, '力学练习三.pdf 第2题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-03-training-003', 'p1b-m1-03-training', 'physics-b-1', 'p1b-m1', 0, '第 3 题', '质量为m的物体最初位于 $x _ { 0 }$ 处,在力 $F = - k / x ^ { 2 }$ 作用下由静止开始沿直线运动,k为一常数,则物体在任一位置x处的速度应为', '["$\\\\sqrt { \\\\frac { k } { m } ( \\\\frac { 1 } { x } - \\\\frac { 1 } { x _ { 0 } } ) }$","$\\\\sqrt { \\\\frac { 2 k } { m } ( \\\\frac { 1 } { x } - \\\\frac { 1 } { x _ { 0 } } ) }$","$\\\\sqrt { \\\\frac { 3 k } { m } ( \\\\frac { 1 } { x } - \\\\frac { 1 } { x _ { 0 } } ) }$","$\\\\sqrt { { \\\\frac { 4 k } { m } } ( { \\\\frac { 1 } { x } } - { \\\\frac { 1 } { x _ { 0 } } } ) }$"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习三.pdf 第3题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-03-training-004', 'p1b-m1-03-training', 'physics-b-1', 'p1b-m1', 2, '第 4 题', '( tk1000A000010957)已知一质量为m 的质点在x 轴上运动,质点只受到指向原点的引力的作用,引力大小与质点离原点的距离x的平方成反比,即$f = - k / x ^ { 2 }$ ,k 是比例常数。设质点在 $x = 8 . 0 0 m$ 时的速度为零,则质点在$x = 2 . 0 0 m$ 处的速率v= o', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["填空题"]'::jsonb, '力学练习三.pdf 第4题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-03-training-005', 'p1b-m1-03-training', 'physics-b-1', 'p1b-m1', 2, '第 5 题', '如图所示,A B两物体质量均为m,用质量不计的定滑轮和细绳连接,并不计摩擦,则A获得的加速度大小为 ,B获得的加速度大小为', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, '/physics/training/p1b-m1-03-training/2e6df1503643fb1daaa5de8ca1759b7e2e9c605a6fd9fae8640749f2d928aa8d.jpg', 1, '["填空题"]'::jsonb, '力学练习三.pdf 第5题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-03-training-006', 'p1b-m1-03-training', 'physics-b-1', 'p1b-m1', 3, '第 6 题', '质量为m的质点,原来静止,在一变力作用下运动,大小随时间变化的关系为$F = F _ { 0 } [ 1 { - } ( t - T ) / T ]$ ,其中 $F _ { 0 }$ T为恒量,求经过2T时间后质点的速度。', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["计算题"]'::jsonb, '力学练习三.pdf 第6题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-03-training-007', 'p1b-m1-03-training', 'physics-b-1', 'p1b-m1', 3, '第 7 题', '质量m = 10kg的物体沿x轴无摩擦地运动,设t = 0时,物体位于原点,速度为零。试求物体在外力F = 4+3x作用下运动了5 m时的速度。', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["计算题"]'::jsonb, '力学练习三.pdf 第7题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-03-training-008', 'p1b-m1-03-training', 'physics-b-1', 'p1b-m1', 3, '第 8 题', '质量为 $m$ 的子弹以速度 $v_0$ 水平射入沙土中，设子弹所受阻力与速度反向，大小与速度成正比，比例系数为 $K$，忽略子弹的重力。求：

（1）子弹射入沙土后，速度随时间变化的函数式；

（2）子弹进入沙土的最大深度。', '[]'::jsonb, '$v(t)=v_0 e^{-rac{K}{m}t}$，$x_{max}=rac{mv_0}{K}$', '[]'::jsonb, NULL, NULL, NULL, '本题属于质点动力学中的变力问题。阻力 $f=-Kv$ 随速度变化，加速度不是常数，不能直接使用匀变速直线运动公式，需回归牛顿第二定律的微分形式。

### 第（1）问：求 $v(t)$

由牛顿第二定律：

$$-Kv = m\\frac{dv}{dt}$$

分离变量：

$$\\frac{dv}{v} = -\\frac{K}{m}dt$$

代入初始条件 $t=0$ 时 $v=v_0$，两边积分：

$$\\int_{v_0}^{v}\\frac{1}{v}dv = \\int_0^t -\\frac{K}{m}dt$$

$$\\ln\\frac{v}{v_0} = -\\frac{K}{m}t$$

$$v(t) = v_0 e^{-\\frac{K}{m}t}$$

### 第（2）问：求最大深度 $x_{max}$

利用链式法则 $a = \\frac{dv}{dt} = v\\frac{dv}{dx}$，代入牛顿第二定律：

$$-Kv = mv\\frac{dv}{dx}$$

因 $v \\neq 0$，两边消去 $v$：

$$-Kdx = mdv$$

代入 $x=0$ 时 $v=v_0$，$x=x_{max}$ 时 $v=0$，积分：

$$\\int_0^{x_{max}} -Kdx = \\int_{v_0}^{0} mdv$$

$$-Kx_{max} = -mv_0$$

$$x_{max} = \\frac{mv_0}{K}$$', NULL, NULL, NULL, 1, '["计算题"]'::jsonb, '力学练习三.pdf 第8题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-04-training-001', 'p1b-m1-04-training', 'physics-b-1', 'p1b-m1', 0, '第 1 题', '质量为 20 g 的子弹沿 X 轴正向以 500 m/s 的速率射入一木块后,与木块一起仍沿 轴正向以50 m/s的速率前进,在此过程中木块所受冲量的大小为', '["10N s·","-10N·s","9N·s","-9N·s。"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习四.pdf 第1题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-04-training-002', 'p1b-m1-04-training', 'physics-b-1', 'p1b-m1', 0, '第 2 题', '如图所示,流水以初速度 $\\nu _ { 1 }$ 进入弯管,流出时的速度为$\\nu _ { 2 }$ ,且 $\\nu _ { 1 } = \\nu _ { 2 } = 5 . 0 ~ \\mathrm { m / s } ,$ ,设每秒流入的水质量为 $q = 1 0 ~ \\mathrm { k g / s }$ ,则在管子转弯处,水对管壁的平均冲力F 大小为', '["50 N","100 N;30°","150 N","200 N。A"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, '/physics/training/p1b-m1-04-training/122af3b51e98d071b7fb8105bb19d2d8969807ece3ed8d762b298ce2006fd3ca.jpg', 1, '["选择题"]'::jsonb, '力学练习四.pdf 第2题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-04-training-003', 'p1b-m1-04-training', 'physics-b-1', 'p1b-m1', 0, '第 3 题', '设作用在质量为 $m { = } 2 . 0 0 \\mathrm { k g }$ 的物体上的力 $F { = } 6 . 0 0 t { + } 3 . 0 0$ (SI)。如果物体在这一力的作用下, 由静止开始沿直线运动,在0到1.50s的时间间隔内,这个力作用在物体上的冲量大小I=', '["$1 1 \\\\mathrm { N } . \\\\mathrm { s } ;$","18Ns","36Ns","60Ns"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习四.pdf 第3题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-04-training-004', 'p1b-m1-04-training', 'physics-b-1', 'p1b-m1', 0, '第 4 题', '作匀速圆周运动的物体运动一周后回到原处,这一周期内物体', '["动量守恒,合外力为零","动量守恒,合外力不为零","动量变化为零,合外力不为零,合外力的冲量为零","动量变化为零,合外力为零。"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习四.pdf 第4题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-04-training-005', 'p1b-m1-04-training', 'physics-b-1', 'p1b-m1', 0, '第 5 题', '用一根细线吊一重物,重物质量为5 kg,重物下面再系一根同样的细线,细线只能经受70 N的拉力.现在突然向下拉一下下面的线.设力最大值为50 N,则', '["下面的线先断","上面的线先断","两根线一起断","两根线都不断"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习四.pdf 第5题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-04-training-006', 'p1b-m1-04-training', 'physics-b-1', 'p1b-m1', 2, '第 6 题', '一物体质量 $M { = } 2 \\mathrm { k g }$ ,在合外力 $\\overrightarrow { F } = \\left( 3 + 2 t \\right) \\ \\overrightarrow { i }$的作用下,从静止开始运动,式中i 为方向一定的单位矢量, 则当 =1 s时物体的速度 $\\vec { \\nu } _ { 1 } =$ C', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["填空题"]'::jsonb, '力学练习四.pdf 第6题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-04-training-007', 'p1b-m1-04-training', 'physics-b-1', 'p1b-m1', 2, '第 7 题', '一质量为 $m _ { \\theta }$ 的斜面原来静止于水平光滑平面上,将一质量为m的木块轻轻放于斜面上,如图,如果此后木块能静止于斜面上,则斜面将', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, '/physics/training/p1b-m1-04-training/e446a8e4a0c6fbf404cc0e4a774ec4f825f5b0f90b35e7c70e7c0a606794196a.jpg', 1, '["填空题"]'::jsonb, '力学练习四.pdf 第7题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-04-training-008', 'p1b-m1-04-training', 'physics-b-1', 'p1b-m1', 3, '第 8 题', '有一门质量为M(含炮弹)的大炮,在一斜面上无摩擦地由静止开始下滑,当滑下L距离时,从炮内沿水平方向射出一发质量为m的炮弹。要使炮车在发射炮弹后的瞬时停止滑动,炮弹的初速度 $\\mathrm { V } _ { 0 }$ 为多少？(设斜面倾角为α)', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, '/physics/training/p1b-m1-04-training/8af6d44f50d63fb35cd90823369e0be426186647d5352d8bbd5b60dbfc3337ee.jpg', 1, '["计算题"]'::jsonb, '力学练习四.pdf 第8题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-04-training-009', 'p1b-m1-04-training', 'physics-b-1', 'p1b-m1', 3, '第 9 题', '一颗子弹在枪筒里前进时所受的合力大小为 $F = 4 0 0 - \\frac { 4 } { 3 } { \\times } 1 0 ^ { 5 } t \\left( N \\right)$ ,子弹从枪口射出时的速率为 $3 0 0 m / s$ 。设子弹离开枪口处合力刚好为零。求：子弹走完枪筒全长所用的时间t;
(2)子弹在枪筒中所受力的冲量I ;
(3)子弹的质量。', '[]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["计算题"]'::jsonb, '力学练习四.pdf 第9题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-05-training-001', 'p1b-m1-05-training', 'physics-b-1', 'p1b-m1', 0, '第 1 题', '对于一个物体系来说,在下列的哪种情况下系统的机械能守恒？', '["合外力为0","合外力不作功","外力和非保守内力都不作功","外力和保守内力都不作功。"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习五.pdf 第1题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-05-training-002', 'p1b-m1-05-training', 'physics-b-1', 'p1b-m1', 0, '第 2 题', '作为相互作用的一对滑动摩擦力,当分别作用在有相对滑动的两物体上时,它们作功之和', '["恒为零","恒为负","恒为正","可能为正、为负或为零。"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习五.pdf 第2题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-05-training-003', 'p1b-m1-05-training', 'physics-b-1', 'p1b-m1', 0, '第 3 题', '如图的系统,物体 A,B置于光滑的桌面上,物体 A和 C,B 和 D 之间摩擦因数均不为零,首先用外力沿水平方向相向推压 A 和 B,使弹簧压缩,后拆除外力,则A和B弹开过程中,对 A、B、C、D组成的系统', '["动量守恒,机械能守恒","动量不守恒,机械能守恒","动量不守恒,机械能不守恒","动量守恒,机械能不一定守恒。"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, '/physics/training/p1b-m1-05-training/c48c724ea33827978b9b82637e9aedd60d9d3fee12b1670dfd0b2efafe951c34.jpg', 1, '["选择题"]'::jsonb, '力学练习五.pdf 第3题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
INSERT INTO public.questions (id, item_id, course_id, module_id, question_type, title, content, options, answer, answers, blanks, tolerance, unit, solution, hint, test_string, image, difficulty, tags, source) VALUES ('q-physics-b-1-p1b-m1-05-training-004', 'p1b-m1-05-training', 'physics-b-1', 'p1b-m1', 0, '第 4 题', '质点在恒力 $\\vec { F } = - 3 \\vec { i } - 5 \\vec { j } + 9 \\vec { k }$作用下,从 $\\vec { r } _ { 1 } = 2 \\vec { i } + 4 \\vec { j } + 3 \\vec { k } \\quad ( \\textrm { m } )$ 运动到$\\vec { r } _ { 2 } = 6 \\vec { i } - \\vec { j } + 1 2 \\vec { k } ( \\mathbf { m } )$ 处,则在此过程中该力做的功为', '["67J","-67J","94J","17J。"]'::jsonb, '', '[]'::jsonb, NULL, NULL, NULL, '', NULL, NULL, NULL, 1, '["选择题"]'::jsonb, '力学练习五.pdf 第4题') ON CONFLICT (id) DO UPDATE SET item_id = EXCLUDED.item_id, course_id = EXCLUDED.course_id, module_id = EXCLUDED.module_id, question_type = EXCLUDED.question_type, title = EXCLUDED.title, content = EXCLUDED.content, options = EXCLUDED.options, answer = EXCLUDED.answer, answers = EXCLUDED.answers, blanks = EXCLUDED.blanks, tolerance = EXCLUDED.tolerance, unit = EXCLUDED.unit, solution = EXCLUDED.solution, hint = EXCLUDED.hint, test_string = EXCLUDED.test_string, image = EXCLUDED.image, difficulty = EXCLUDED.difficulty, tags = EXCLUDED.tags, source = EXCLUDED.source;
COMMIT;